#!/bin/bash


screen -ls | grep -q homeauto 
if [ $? -eq 0 ]
then
    echo "homeauto screen session running $(date)"
else
    echo start homeauto screen session $(date)
    (cd /home/pi/p/baker-house; screen -S bakerhouse -d -m -c /home/pi/p/baker-house/scripts/homeautoscreenrc )
fi
